id = "sight"
name = "Sight - Stata Language Server"
description = "Language support for Stata using LSP"
version = "0.1.10"
schema_version = 1
authors = ["Jonathan Marc Bearak"]
repository = "https://github.com/jbearak/sight-zed"
themes = []
icon_themes = []
languages = ["languages/stata"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.stata]
path = "grammars/stata.wasm"

[language_servers.sight]
name = "Sight"
language = "Stata"
