name = "Stata"
grammar = "stata"
path_suffixes = ["do", "ado", "doh", "mata"]
line_comments = ["// ", "* "]
block_comment = ["/* ", " */"]
autoclose_before = ";:.,=}])>'\"` \n\t"

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
  { start = "`", end = "'", close = true, newline = false },
]

word_characters = ["_"]
